apiVersion: v1
kind: Secret
metadata:
  name: clc-kv-secret
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: "azure/kv"
data:
  clientid: {{ default "" .Values.client_id | b64enc | quote }}
  clientsecret: {{ default "" .Values.client_secret | b64enc | quote }}